# Generated by Django 4.2.4 on 2023-08-17 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("l_info", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="l_comment",
            old_name="l_author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="l_comment",
            old_name="l_comment",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="l_comment",
            old_name="l_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="l_comment",
            old_name="l_post",
            new_name="post",
        ),
    ]
