# Generated by Django 4.2.4 on 2023-08-16 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("k_sellboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="bootcampus_sellproduct",
        ),
    ]
