# Generated by Django 4.2.4 on 2023-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcuser", "0002_bcuser_nickname"),
        ("k_sellboard", "0004_product_category_product_writer_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="jjim",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="jjims",
            field=models.ManyToManyField(
                blank=True, related_name="jjims_chats", to="bcuser.bcuser"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
