# Generated by Django 4.2.4 on 2023-08-09 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("h_justchat", "0002_alter_h_chat_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="h_chat",
            table="h_chat",
        ),
    ]
