# Generated by Django 4.2.4 on 2023-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("h_justchat", "0006_alter_h_chat_h_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="h_chat",
            name="h_category",
            field=models.CharField(
                choices=[("news", "소식"), ("friendship", "친목"), ("etc", "기타")],
                default="news",
                max_length=64,
                verbose_name="카테고리",
            ),
        ),
    ]
