# Generated by Django 4.2.4 on 2023-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("h_justchat", "0009_h_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="h_comment",
            name="comment",
            field=models.CharField(max_length=256, verbose_name="댓글 내용"),
        ),
    ]
