# Generated by Django 4.2.4 on 2023-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("h_justchat", "0010_alter_h_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="h_chat",
            name="h_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
