# Generated by Django 4.2.4 on 2023-08-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bcuser", "0001_initial"),
        ("h_justchat", "0012_rename_h_views_h_chat_h_click"),
    ]

    operations = [
        migrations.AddField(
            model_name="h_chat",
            name="h_voters",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_chats", to="bcuser.bcuser"
            ),
        ),
        migrations.AddField(
            model_name="h_chat",
            name="h_votes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
