# Generated by Django 4.2.4 on 2023-08-16 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bcuser", "0002_bcuser_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="e_Duo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "e_category",
                    models.CharField(
                        choices=[
                            ("PC", "PC"),
                            ("닌텐도", "닌텐도"),
                            ("플스", "플스"),
                            ("엑스박스", "엑스박스"),
                            ("기타", "기타"),
                        ],
                        default="news",
                        max_length=64,
                        verbose_name="카테고리",
                    ),
                ),
                ("e_title", models.CharField(max_length=128, verbose_name="제목")),
                ("e_contents", models.TextField(verbose_name="내용")),
                (
                    "e_register_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록날짜"
                    ),
                ),
                ("e_click", models.PositiveIntegerField(default=0)),
                ("e_votes", models.PositiveIntegerField(default=0)),
                (
                    "e_voters",
                    models.ManyToManyField(
                        blank=True, related_name="upvoted_duos", to="bcuser.bcuser"
                    ),
                ),
                (
                    "e_writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bcuser.bcuser",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "2인모집",
                "verbose_name_plural": "2인모집글들",
                "db_table": "e_duo",
            },
        ),
        migrations.CreateModel(
            name="e_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=256, verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bcuser.bcuser",
                        verbose_name="작성자",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="e_duo.e_duo",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글들",
            },
        ),
    ]
