# Generated by Django 4.2.4 on 2023-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_duo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="e_duo",
            name="e_need",
            field=models.IntegerField(default=1, max_length=16, verbose_name="정원"),
            preserve_default=False,
        ),
    ]
