# Generated by Django 4.2.4 on 2023-08-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_duo", "0002_e_duo_e_need"),
    ]

    operations = [
        migrations.AlterField(
            model_name="e_duo",
            name="e_need",
            field=models.IntegerField(verbose_name="정원"),
        ),
    ]
