# Generated by Django 4.2.4 on 2023-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="buyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="상품명")),
                ("price", models.IntegerField(verbose_name="희망가격")),
                ("description", models.TextField(verbose_name="상품설명")),
                (
                    "register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록날짜"),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품들",
                "db_table": "bootcampus_buyproduct",
            },
        ),
    ]
