# Generated by Django 4.2.4 on 2023-08-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bcuser", "0002_bcuser_nickname"),
        ("j_buyboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="writer",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bcuser.bcuser",
                verbose_name="작성자",
            ),
        ),
    ]
