# Generated by Django 4.2.4 on 2023-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("j_buyboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
