# Generated by Django 4.2.4 on 2023-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("j_buyboard", "0002_product_sold_out_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1, verbose_name="재고"),
        ),
    ]
