# Generated by Django 4.2.4 on 2023-08-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("j_buyboard", "0003_j_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("본체 ", "본체 "),
                    ("타이틀 ", "타이틀 "),
                    ("주변기기 ", "주변기기 "),
                    ("기타", "기타"),
                ],
                default="news",
                max_length=64,
                verbose_name="카테고리",
            ),
        ),
    ]
