# Generated by Django 4.2.4 on 2023-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bcuser", "0002_bcuser_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=64, verbose_name="게시판명")),
                ("category", models.CharField(max_length=64, verbose_name="카테고리")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("click", models.IntegerField(verbose_name="조회수")),
                ("date", models.DateTimeField(verbose_name="일자")),
                (
                    "origin",
                    models.IntegerField(blank=True, null=True, verbose_name="원글"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=64, verbose_name="게시판명")),
                ("category", models.CharField(max_length=64, verbose_name="카테고리")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("click", models.IntegerField(verbose_name="조회수")),
                ("date", models.DateTimeField(verbose_name="일자")),
                (
                    "origin",
                    models.IntegerField(blank=True, null=True, verbose_name="원글"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=64, verbose_name="게시판명")),
                ("category", models.CharField(max_length=64, verbose_name="카테고리")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("click", models.IntegerField(verbose_name="조회수")),
                ("date", models.DateTimeField(verbose_name="일자")),
                (
                    "origin",
                    models.IntegerField(blank=True, null=True, verbose_name="원글"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=64, verbose_name="게시판명")),
                ("category", models.CharField(max_length=64, verbose_name="카테고리")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("click", models.IntegerField(verbose_name="조회수")),
                ("date", models.DateTimeField(verbose_name="일자")),
                (
                    "origin",
                    models.IntegerField(blank=True, null=True, verbose_name="원글"),
                ),
            ],
        ),
    ]
