# Generated by Django 4.2.4 on 2023-08-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0002_remove_mypage_tags_mypage_mypage_writer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mypage",
            name="time",
        ),
        migrations.DeleteModel(
            name="TimeChoice",
        ),
    ]
