# Generated by Django 4.2.4 on 2023-08-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("o_mypage", "0003_remove_mypage_time_delete_timechoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypage",
            name="mypage_writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
