# Generated by Django 4.2.4 on 2023-08-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0005_alter_mypage_mypage_writer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mypage",
            old_name="mypage_writer",
            new_name="writer",
        ),
    ]
