# Generated by Django 4.2.4 on 2023-08-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0006_rename_mypage_writer_mypage_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypage",
            name="voice",
            field=models.CharField(
                choices=[("보이스 가능", "보이스 가능"), ("보이스 불가능", "보이스 불가능")],
                default="보이스 가능",
                max_length=10,
                verbose_name="음성대화",
            ),
        ),
    ]
