# Generated by Django 4.2.4 on 2023-08-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0007_mypage_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypage",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/profile_images",
                verbose_name="프로필 이미지",
            ),
        ),
        migrations.AlterField(
            model_name="mypage",
            name="voice",
            field=models.CharField(
                choices=[("가능", "가능"), ("불가능", "불가능")],
                default="음성채팅 가능",
                max_length=10,
                verbose_name="음성대화",
            ),
        ),
    ]
