# Generated by Django 4.2.4 on 2023-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0008_mypage_profile_image_alter_mypage_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypage",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images",
                verbose_name="프로필 이미지",
            ),
        ),
    ]
