# Generated by Django 4.2.4 on 2023-08-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0010_remove_mypage_profile_image_mypage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mypage",
            name="image",
        ),
    ]
