# Generated by Django 4.2.4 on 2023-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("o_mypage", "0011_remove_mypage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypage",
            name="introduction",
            field=models.TextField(blank=True, null=True, verbose_name="자기소개"),
        ),
    ]
