# Generated by Django 4.2.4 on 2023-08-09 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bcuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="h_Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h_title", models.CharField(max_length=128, verbose_name="제목")),
                ("h_contents", models.TextField(verbose_name="내용")),
                (
                    "h_register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록날짜"),
                ),
                (
                    "h_writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bcuser.bcuser",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "잡담",
                "verbose_name_plural": "잡담들",
                "db_table": "bootcampus_product",
            },
        ),
    ]
