# Generated by Django 4.2.4 on 2023-08-09 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("h_justchat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="h_chat",
            table="gg_chat",
        ),
    ]
