# Generated by Django 4.2.4 on 2023-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("h_justchat", "0004_alter_h_chat_h_register_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="h_chat",
            name="h_category",
            field=models.CharField(
                choices=[("소식", "소식"), ("친목", "친목"), ("기타", "기타")],
                default="소식",
                max_length=64,
                verbose_name="카테고리",
            ),
        ),
    ]
