# Generated by Django 4.2.4 on 2023-08-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bcuser", "0001_initial"),
        ("c_notice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="c_Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("contents", models.TextField(verbose_name="내용")),
                (
                    "register_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
                ),
            ],
            options={
                "verbose_name": "공지 게시글",
                "verbose_name_plural": "공지 게시글들",
                "db_table": "notice_board",
            },
        ),
        migrations.CreateModel(
            name="c_Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="태그명")),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
                ),
            ],
            options={
                "verbose_name": "공지 태그",
                "verbose_name_plural": "공지 태그",
                "db_table": "notice_tag",
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="c_board",
            name="tags",
            field=models.ManyToManyField(to="c_notice.c_tag", verbose_name="태그"),
        ),
        migrations.AddField(
            model_name="c_board",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bcuser.bcuser",
                verbose_name="작성자",
            ),
        ),
    ]
