# Generated by Django 4.2.4 on 2023-08-08 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("c_notice", "0002_c_board_c_tag_delete_product_c_board_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="c_board",
            options={"verbose_name": "상품", "verbose_name_plural": "상품들"},
        ),
        migrations.RemoveField(
            model_name="c_board",
            name="register_dttm",
        ),
        migrations.RemoveField(
            model_name="c_tag",
            name="registered_dttm",
        ),
        migrations.AddField(
            model_name="c_board",
            name="register_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="등록날짜"
            ),
        ),
        migrations.AlterField(
            model_name="c_board",
            name="contents",
            field=models.TextField(verbose_name="본문"),
        ),
        migrations.AlterField(
            model_name="c_board",
            name="title",
            field=models.CharField(max_length=256, verbose_name="글제목"),
        ),
        migrations.AlterModelTable(
            name="c_board",
            table="bootcampus_product",
        ),
    ]
