# Generated by Django 4.2.4 on 2023-08-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("c_notice", "0004_alter_c_board_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="c_board",
            name="register_date",
        ),
    ]
