# Generated by Django 4.2.4 on 2023-08-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("c_notice", "0005_remove_c_board_register_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="c_board",
            name="tags",
        ),
        migrations.DeleteModel(
            name="c_Tag",
        ),
    ]
