# Generated by Django 4.2.4 on 2023-08-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_notice", "0006_remove_c_board_tags_delete_c_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="c_board",
            name="category",
            field=models.CharField(
                choices=[("steam", "스팀"), ("nintendo", "닌텐도")],
                default="steam",
                max_length=128,
                verbose_name="카테고리",
            ),
        ),
    ]
