# Generated by Django 4.2.4 on 2023-08-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_notice", "0007_c_board_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="c_board",
            name="category",
            field=models.CharField(
                choices=[("스팀", "스팀"), ("닌텐도", "닌텐도")],
                default="steam",
                max_length=128,
                verbose_name="카테고리",
            ),
        ),
    ]
